import time
from fastapi import FastAPI, Request

app = FastAPI() 


'''
Middleware is a function works with every request before it is 
processed by any specific path operation. And also with every 
response before returning it. 

- It takes each request that comes to your application. 
- It can run any type of code to that request
- It passes the request to be processed by the rest of application. 
- It then takes the response generated by application. 
'''
@app.middleware("http")

# ======= Middleware ===========
async def add_process_time_header(request: Request, call_next):
    start_time = time.perf_counter() 
    response = await call_next(request)
    process_time = time.perf_counter() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response